version: '3'

services:
    db:
        image: mariadb:10.7.8
        volumes:
            - ./db:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=wordpress
            - MYSQL_USER=manager
            - MYSQL_PASSWORD=secret
    wp:
        build: 
            context: ./
            dockerfile: Dockerfile.yml
        # image: wordpress:6.1.1
        # command: ["/usr/local/bin/docker-php-ext-install pdo pdo_mysql","/usr/local/bin/docker-php-ext-install pdo pdo_mysql"]
        depends_on:
            - db
        volumes:
            - ./wp:/var/www/html
        environment:
            - WORDPRESS_DB_USER=manager
            - WORDPRESS_DB_PASSWORD=secret
            - WORDPRESS_DB_HOST=db
        ports:
            - 8080:80

volumes:
    data:
